import { useTranslation } from "react-i18next";
import { setLang, type Lang } from ".";

export const languageOptions: Array<{ code: Lang; short: string; label: string }> = [
  { code: "en", short: "EN", label: "English" },
  { code: "ar", short: "AR", label: "العربية" },
  { code: "ms", short: "MS", label: "Bahasa Melayu" },
];

const translations = {
  en: {
    common: { language: "Language", brandSubtitle: "MMU student hub", signIn: "Sign in", signOut: "Sign out", dismiss: "Dismiss", loading: "Loading…" },
    nav: { label: "CampusPulse pages", campus: "MY CAMPUS", home: "Home", discover: "All updates", attendance: "Attendance", calendar: "Calendar", notifications: "Notifications", settings: "Settings", open: "Open navigation", close: "Close navigation", messages: "Messages", closeOverlay: "Close navigation overlay", mmu: "MMU", mmuHint: "Opens the MMU website in a new tab" },
    roles: { student: "Student", academicProfile: "Academic profile", studentAcademy: "Bachelor of Computer Science", autoAssigned: "Auto-assigned" },
    topbar: { searchLabel: "Search CampusPulse", search: "Search deadlines, events, clubs…", synced: "Campus sources synced", notifications: "View notifications" },
    authVisual: { alt: "Students moving through a connected campus", badge: "One campus. One clear view.", title1: "Know what matters.", title2: "Before you miss it.", description: "Your deadlines, events and opportunities—organised around you.", deadline: "NEXT DEADLINE", deadlineValue: "AI Ethics · 12:00 PM", match: "NEW MATCH", matchValue: "Scholarship closes Monday", footer: "© 2026 CampusPulse · MMU Hack Day" },
    login: { eyebrow: "WELCOME BACK", title: "Sign in to your campus.", description: "Continue to your personal CampusPulse workspace.", email: "Email address", emailPlaceholder: "name@example.com", password: "Password", keep: "Keep me signed in", forgot: "Forgot password?", submit: "Sign in", loading: "Signing in…", newAccount: "New to CampusPulse?", create: "Create your account", secure: "Your session is protected with secure server cookies.", error: "Enter a valid email and a password of at least 6 characters.", failed: "We could not sign you in. Check your details and try again.", show: "Show password", hide: "Hide password" },
    signup: { eyebrow: "CREATE YOUR SPACE", title: "Make campus feel personal.", description: "Set up your profile and tune what CampusPulse brings forward.", first: "First name", last: "Last name", email: "Email address", emailPlaceholder: "name@example.com", address: "Address", addressPlaceholder: "Street address", password: "Password", passwordPlaceholder: "At least 8 characters", agree: "I agree to the", terms: "Terms", and: "and", privacy: "Privacy Policy", submit: "Create account", loading: "Creating account…", failed: "We could not create your account.", existing: "Already have an account?", signIn: "Sign in" },
    recovery: { eyebrow: "ACCOUNT RECOVERY", title: "Reset your password.", description: "Enter your email and we will send a secure recovery link.", email: "Email address", emailPlaceholder: "name@example.com", continue: "Send reset link", loading: "Sending…", failed: "We could not send the recovery email.", back: "Back to sign in", success: "Check your inbox", prepared: "A recovery link was sent to {{email}}." },
    verify: { eyebrow: "VERIFY YOUR EMAIL", title: "Enter your verification code.", description: "Use the six-digit code sent to your email to activate your account.", email: "Email address", code: "Verification code", submit: "Verify account", loading: "Verifying…", success: "Email verified. You can now sign in.", failed: "The verification code could not be accepted.", resend: "Send a new code", resendFailed: "We could not resend the code." },
    reset: { eyebrow: "SECURE RESET", title: "Choose a new password.", description: "Use at least eight characters and keep it unique to CampusPulse.", password: "New password", confirm: "Confirm new password", submit: "Update password", loading: "Updating…", mismatch: "The passwords do not match.", missingToken: "This reset link is missing its security token.", failed: "We could not update your password." },
    landing: { features: "Features", how: "How it works", eyebrow: "Your campus, finally in sync", title1: "Know what matters.", title2: "Before you miss it.", subtitle: "CampusPulse gathers deadlines, events, announcements and opportunities, then turns them into one personal daily plan.", start: "Get started", meet: "See how it works", proof1: "unified calendar", proof2: "campus companion", proof3: "missed deadlines", friday: "Friday, 29 August", morning: "Good morning, Aina.", daily: "YOUR DAILY PULSE", three: "Three things need your attention today.", review: "Review", today: "Today", viewAll: "View all", ethics: "AI Ethics assignment", due: "Due in 2 hours", workshop: "Tech Club workshop", lab: "FCI XR Lab", briefing: "Scholarship briefing", online: "Online session", insight: "SMART INSIGHT", conflict: "I found a schedule conflict.", conflictText: "Your workshop overlaps with a project meeting. Review your calendar to find a better time.", fix: "Review schedule", opportunity: "New opportunity:", opportunityText: "Yayasan scholarship applications close on Monday.", featureKicker: "ONE CAMPUS. ONE CLEAR VIEW.", featureTitle: "Everything it gathers,", featureAccent: "and everything it clears up.", featureText: "Focused features, concrete benefits, visible proof and one direct route into the product.", f1Title: "One smart calendar", f1Text: "Course deadlines, club events and opportunities share one timeline with conflict detection.", f2Title: "Personal, not noisy", f2Text: "Updates are ranked around your interests and urgency instead of broadcast to everyone.", f3Title: "Clear next steps", f3Text: "Compare priorities and move directly to the item that needs attention.", storyKicker: "HOW CAMPUSPULSE WORKS", storyTitle1: "From scattered updates", storyTitle2: "to one useful next step.", gather: "Gather", gatherText: "Bring academic notices, events, clubs and scholarships into one feed.", understand: "Understand", understandText: "Match every item against the student’s interests and calendar.", act: "Act", actText: "Explain priorities and prepare clear next steps for the student.", sources: "campus source types", timeline: "unified student timeline", available: "always available", controlled: "student-controlled actions", finalKicker: "YOUR CAMPUS IS ALREADY MOVING", finalTitle: "Move with it.", finalText: "Open CampusPulse and experience the daily brief, discovery feed, calendar and notifications.", enter: "Enter CampusPulse", footer: "Designed for MMU Hack Day 2026 · Frontend demo" },
    dashboard: { kicker: "FRIDAY · 29 AUGUST 2026", greeting: "Good morning, Aina.", subtitle: "Here is the clearest path through your campus day.", viewCalendar: "View calendar", daily: "PULSE · DAILY BRIEF", dailyTitle: "Three things need your attention today.", dailyText: "Your AI Ethics assignment is due at noon. I also found one schedule conflict and a scholarship that closes in three days.", review: "Review schedule", deadlines: "Upcoming deadlines", deadlinesNote: "2 due this week", events: "Events for you", eventsNote: "3 newly matched", saved: "Saved opportunities", savedNote: "1 closing soon", today: "TODAY", agenda: "Your agenda", fullCalendar: "Full calendar", rest: "See the rest of your day", next: "NEXT UP", focus: "Focus window", until: "until your deadline", assignment: "AI Ethics assignment", progress: "TDS 2111 · 80% complete", openAssignment: "Open assignment", personal: "PERSONALISED FOR YOU", attention: "Worth your attention", explore: "Explore everything", source: "Source:", details: "View details", save: "Save", remove: "Remove" },
    status: { kicker: "STUDENT STATUS", title: "At a glance", attendance: "Attendance", grades: "Grades", level: "Current level", levelValue: "Year 2", deadlines: "Deadlines", risk: "One course requires immediate attendance action" },
    attendance: {
      kicker: "ATTENDANCE, CLEARLY TRACKED", title: "Attendance", subtitle: "Every absence reduces the course percentage by 7.14%.", submitExcuse: "Submit medical excuse", overall: "Overall attendance", courseCount: "Across {{count}} active courses", updated: "Across 5 active courses", deduction: "deducted for every missed class", barCourses: "courses below the 70% threshold", monitoring: "COURSE MONITORING", byCourse: "Attendance by course", threshold: "Below 70% enters attendance bar", attendance: "Attendance", absences: "absences", contactStaff: "Contact faculty staff", attended: "Attended", missed: "Missed", marking: "Saving…",
      courses: { c1: "AI Ethics", c2: "Database Systems", c3: "Software Engineering", c4: "Human–Computer Interaction", c5: "Data Communications" },
      level: { good: "On track", notice: "First notice", warning: "Second warning", elevated: "Third warning", critical: "Final warning", barred: "Attendance bar" },
      message: { good: "Your attendance is healthy.", notice: "You missed one class. A smart reminder has been issued.", warning: "Second absence recorded. This warning is now yellow.", elevated: "Third absence recorded. Immediate improvement is recommended.", critical: "Fourth absence recorded. Your attendance is close to the bar threshold.", barred: "Your attendance is below 70%. Visit faculty staff and your lecturer, then submit any medical excuses for review." },
    },
    discover: { alt: "Students moving through a connected digital campus", kicker: "DISCOVER YOUR CAMPUS", title1: "Opportunities that fit", title2: "where you are going.", subtitle: "Events, scholarships, clubs and academic support—filtered around your interests.", search: "Search campus opportunities", all: "All", academic: "Academic", event: "Event", scholarship: "Scholarship", club: "Club", feed: "CURATED FEED", matches: "{{count}} matches for you", updated: "Updated from 12 campus sources", open: "Open", empty: "No matches yet", emptyText: "Try a different phrase or category." },
    calendar: { kicker: "YOUR TIME, IN ONE PLACE", title: "Calendar", subtitle: "Academic deadlines and campus life, without the collisions.", add: "Add personal item", ready: "Personal item ready.", readyText: "This frontend demo keeps it for the current session.", range: "24–30 August 2026", week: "Week", month: "Month", today: "Today", previous: "Previous period", next: "Next period", noEvents: "No events", showMore: "+{{count}} more", showLess: "Show less", submittedKicker: "COMPLETED WORK", submitted: "Submitted", submittedHint: "Completed deadlines are removed from your active calendar and kept here.", mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri", sat: "Sat", sun: "Sun", entryCount: "{{count}} items", items: "3 items", event: "1 event", insight: "PULSE INSIGHT", insightTitle: "Your busiest window is Friday, 12–3 PM.", insightText: "I can move your flexible project check-in so you have a 45-minute focus buffer before the workshop.", resolve: "Resolve conflict" },
    notifications: { kicker: "STAY AHEAD, NOT OVERWHELMED", title: "Notifications", subtitle: "Only changes that deserve your attention.", mark: "Mark all as read", emailBrief: "Email me my brief", emailSending: "Sending…", emailSent: "Brief sent to {{email}} ({{count}} items).", emailEmpty: "Brief sent to {{email}} — nothing active right now.", emailFailed: "We could not send your brief.", all: "All", unread: "Unread", count: "{{count}} unread", empty: "You are all caught up", emptyText: "New campus updates will appear here.", n1Title: "Deadline moved forward", n1Body: "AI Ethics assignment is now due today at 12:00 PM.", n1Time: "8 min ago", n2Title: "Pulse found a conflict", n2Body: "Your product workshop overlaps with the project-team check-in.", n2Time: "24 min ago", n3Title: "Scholarship closing soon", n3Body: "The Maybank FutureReady application closes in three days.", n3Time: "1 hr ago", n4Title: "New event for you", n4Body: "A Gemini prototyping meetup matches your AI and product interests.", n4Time: "Yesterday", n5Title: "Robotics Club intake", n5Body: "Applications are open for build, software and design teams.", n5Time: "Yesterday", n6Title: "First absence recorded", n6Body: "You missed AI Ethics. Your attendance is now 92.86%.", n6Time: "22 min ago", n7Title: "Second absence recorded", n7Body: "Database Systems attendance is now 85.72%. Please review your schedule.", n7Time: "18 min ago", n8Title: "Third absence recorded", n8Body: "Software Engineering attendance has dropped to 78.58%.", n8Time: "12 min ago", n9Title: "Fourth absence recorded", n9Body: "Human–Computer Interaction attendance is now 71.44%. Immediate action is required.", n9Time: "5 min ago", n10Title: "Attendance bar reached", n10Body: "Data Communications is below 70%. Visit faculty staff and your lecturer with any medical excuses.", n10Time: "Just now" },
    studyPlan: { kicker: "AI STUDY PLAN", title: "Plan my next few days", text: "Built from your courses, upcoming deadlines and attendance.", generate: "Generate plan", loading: "Building your plan…", failed: "The plan could not be generated. Try again.", empty: "No tasks to plan yet.", minutes: "{{count}} min" },
    mmu: { kicker: "MMU SERVICES", title: "Your university portals", subtitle: "The four systems your degree actually runs on — one tap away.", open: "Open portal", external: "Opens in a new tab", mainName: "MMU Official Site", mainText: "The university's public home: faculties, news, academic calendar, admissions and campus announcements.", mainTags: "Faculties|News|Admissions", clicName: "CLiC Student Portal", clicText: "Your student record: attendance percentage per subject, fee statements and payment, and course registration each semester.", clicTags: "Attendance|Fees|Registration", ebwiseName: "eBWise Learning", ebwiseText: "Course delivery: lecture materials, assignment briefs, lab submissions, quizzes and midterm examinations.", ebwiseTags: "Assignments|Labs|Quizzes", teamsName: "Microsoft Teams", teamsText: "Live and recorded lectures, tutorial sessions, and the assignments some lecturers collect through Teams.", teamsTags: "Lectures|Meetings|Files" },
    messages: { kicker: "EVERY CHANNEL, ONE INBOX", title: "Messages", subtitle: "Teams, Outlook, Blackboard and Moodle in one place.", all: "All", unread: "Unread", count: "{{count}} unread", progress: "Progress", done: "Done", markRead: "Mark as read", dismiss: "Dismiss", empty: "No messages yet", emptyText: "Campus channels will deliver here once your feed is generated.", track: "Track this", tracking: "Tracking" },
    profile: { kicker: "PERSONALISE YOUR PULSE", title: "Your profile", subtitle: "These details decide what CampusPulse brings forward.", saved: "Profile saved. Your feed was regenerated.", campus: "Campus", campusValue: "Cyberjaya", year: "Study year", yearValue: "Year 2", preferences: "DISCOVERY PREFERENCES", interests: "Your interests", interestsText: "Choose topics to tune recommendations.", save: "Save preferences", academicKicker: "ACADEMIC PROFILE", academicTitle: "Courses and academic details", academicText: "Personalisation matches campus updates against these. Pick at least one course and one interest.", faculty: "Faculty", major: "Major", yearOfStudy: "Year of study", coursesLabel: "Your courses", otherFaculty: "Other courses", saveGenerate: "Save and generate my feed", generating: "Generating your feed…", requireBoth: "Pick at least one course and one interest before saving.", noCourses: "The course catalog is empty — your interests alone will drive personalisation for now.", coursesFailed: "The course catalog could not be loaded. You can still save the rest.", requireInterest: "Pick at least one interest before saving.", onboarding: "Finish this once so CampusPulse can personalise your feed.", ai: "Artificial intelligence", design: "Product design", scholarships: "Scholarships", hackathons: "Hackathons", entrepreneurship: "Entrepreneurship", sustainability: "Sustainability", robotics: "Robotics", volunteering: "Volunteering" },
    data: {
      i1: { title: "AI Ethics assignment", date: "29 Aug", location: "MMLS submission portal", description: "Final reflection and responsible AI case analysis.", source: "TDS 2111 · Course announcement" },
      i2: { title: "Tech Club product workshop", date: "29 Aug", location: "FCI XR Lab", description: "Rapid prototyping workshop for student builders.", source: "IT Society · Event notice" },
      i3: { title: "Yayasan scholarship briefing", date: "29 Aug", location: "Microsoft Teams", description: "Eligibility, documents and application walkthrough.", source: "Student Affairs · Scholarship desk" },
      i4: { title: "Campus sustainability challenge", date: "30 Aug", location: "CLC Concourse", description: "Pitch practical ideas for a greener MMU campus.", source: "Sustainability Office" },
      i5: { title: "Database systems quiz", date: "31 Aug", location: "MMLS online quiz", description: "Covers normalization, transactions and indexing.", source: "TDB 2201 · Course announcement" },
      i11: { title: "Maybank FutureReady Scholarship", date: "Closes 1 Sep", location: "Online application", description: "Funding and mentorship for Malaysian undergraduates with strong community involvement.", source: "MMU Student Affairs" },
      i12: { title: "Google Developer Groups Campus Meetup", date: "3 Sep", location: "FCI Lecture Theatre 2", description: "Lightning talks, networking and hands-on Gemini prototyping with student developers.", source: "GDG on Campus MMU" },
      i13: { title: "Robotics Club intake 2026", date: "5 Sep", location: "Engineering Maker Lab", description: "Join the build, software or design team. Beginners are welcome.", source: "MMU Robotics Club" },
      i14: { title: "Academic writing clinic", date: "6 Sep", location: "Learning Point, Library", description: "Bring a draft and receive one-to-one feedback on structure and citations.", source: "MMU Library" },
    },
    legal: { back: "Back to sign up", effective: "Effective 29 August 2026", termsKicker: "CAMPUSPULSE LEGAL", termsTitle: "Terms of Use", termsIntro: "These terms explain how you may use the CampusPulse hack-day service. By creating an account or using the service, you agree to these terms.", t1: "1. Service status", tp1: "CampusPulse is a hack-day project and is not an official MMU service. Do not use it as your only source for important campus information.", t2: "2. Your account", tp2: "Your authenticated session is handled by the configured CampusPulse API. You are responsible for accurate information and securing your device.", t3: "3. Acceptable use", tp3: "Use CampusPulse only for lawful student and demonstration purposes. Do not disrupt it, impersonate others, or submit harmful content.", t4: "4. Information accuracy", tp4: "Some information may be sample or synchronized content. Confirm critical dates and records through official MMU channels.", t5: "5. Changes", tp5: "The service and these terms may change as the project develops.", termsCallout: "Questions about these terms can be directed to the CampusPulse hack-day team.", privacyKicker: "YOUR DATA, CLEARLY EXPLAINED", privacyTitle: "Privacy Policy", privacyIntro: "This policy describes how CampusPulse handles information you enter and data returned by its configured API.", p1: "1. What is stored", pp1: "CampusPulse may process your name, email, address, academic profile, preferences, session state, and relevant campus information.", p2: "2. Where the information goes", pp2: "When the API is available, account and profile data are sent to the configured CampusPulse backend. A limited local fallback may retain session display data on this device during development.", p3: "3. How it is used", pp3: "Information is used to authenticate you, personalize updates, and present your academic dashboard.", p4: "4. Sharing and selling", pp4: "CampusPulse does not sell your information or share it with advertisers. Authorized campus services may provide data required for the product.", p5: "5. Your choices", pp5: "You can sign out, clear local site data, and contact the project team about account data.", p6: "6. Service integrations", pp6: "Backend, campus-source, and AI integrations must follow the approved data, security, and consent requirements before production use.", privacyCallout: "Questions about privacy can be directed to the CampusPulse hack-day team." },
  },
  ar: {
    common: { language: "اللغة", brandSubtitle: "بوابة طلاب MMU", signIn: "تسجيل الدخول", signOut: "تسجيل الخروج", dismiss: "إغلاق", loading: "جارٍ التحميل…" },
    nav: { label: "صفحات CampusPulse", campus: "جامعتي", home: "الرئيسية", discover: "كل التحديثات", attendance: "الحضور", calendar: "التقويم", notifications: "الإشعارات", settings: "الإعدادات", open: "فتح القائمة", close: "إغلاق القائمة", messages: "الرسائل", closeOverlay: "إغلاق خلفية القائمة", mmu: "MMU", mmuHint: "يفتح موقع MMU في تبويب جديد" },
    roles: { student: "طالب", academicProfile: "الملف الأكاديمي", studentAcademy: "بكالوريوس علوم الحاسب", autoAssigned: "تعيين تلقائي" },
    topbar: { searchLabel: "البحث في CampusPulse", search: "ابحث عن المواعيد والفعاليات والأندية…", synced: "تمت مزامنة مصادر الجامعة", notifications: "عرض الإشعارات" },
    authVisual: { alt: "طلاب داخل حرم جامعي متصل", badge: "جامعة واحدة. رؤية واضحة.", title1: "اعرف ما يهم.", title2: "قبل أن يفوتك.", description: "مواعيدك وفعالياتك وفرصك مرتبة حول احتياجاتك.", deadline: "الموعد القادم", deadlineValue: "أخلاقيات الذكاء الاصطناعي · 12:00 م", match: "فرصة جديدة", matchValue: "المنحة تغلق يوم الاثنين", footer: "© 2026 CampusPulse · يوم MMU للابتكار" },
    login: { eyebrow: "مرحبًا بعودتك", title: "سجّل دخولك إلى جامعتك.", description: "تابع إلى مساحة CampusPulse الشخصية.", email: "البريد الإلكتروني", emailPlaceholder: "name@example.com", password: "كلمة المرور", keep: "إبقائي مسجلًا", forgot: "نسيت كلمة المرور؟", submit: "تسجيل الدخول", loading: "جارٍ تسجيل الدخول…", newAccount: "جديد في CampusPulse؟", create: "أنشئ حسابك", secure: "جلستك محمية بملفات تعريف ارتباط آمنة من الخادم.", error: "أدخل بريدًا صحيحًا وكلمة مرور من 6 أحرف على الأقل.", failed: "تعذر تسجيل الدخول. تحقق من بياناتك وحاول مجددًا.", show: "إظهار كلمة المرور", hide: "إخفاء كلمة المرور" },
    signup: { eyebrow: "أنشئ مساحتك", title: "اجعل تجربتك الجامعية شخصية.", description: "أنشئ ملفك واضبط ما يعرضه CampusPulse لك.", first: "الاسم الأول", last: "اسم العائلة", email: "البريد الإلكتروني", emailPlaceholder: "name@example.com", address: "العنوان", addressPlaceholder: "عنوان الشارع", password: "كلمة المرور", passwordPlaceholder: "8 أحرف على الأقل", agree: "أوافق على", terms: "الشروط", and: "و", privacy: "سياسة الخصوصية", submit: "إنشاء الحساب", loading: "جارٍ إنشاء الحساب…", failed: "تعذر إنشاء الحساب.", existing: "لديك حساب بالفعل؟", signIn: "تسجيل الدخول" },
    recovery: { eyebrow: "استعادة الحساب", title: "أعد تعيين كلمة المرور.", description: "أدخل بريدك وسنرسل رابط استعادة آمنًا.", email: "البريد الإلكتروني", emailPlaceholder: "name@example.com", continue: "إرسال رابط الاستعادة", loading: "جارٍ الإرسال…", failed: "تعذر إرسال رسالة الاستعادة.", back: "العودة لتسجيل الدخول", success: "تحقق من بريدك", prepared: "أُرسل رابط الاستعادة إلى {{email}}." },
    verify: { eyebrow: "تأكيد البريد الإلكتروني", title: "أدخل رمز التحقق.", description: "استخدم الرمز المكون من ستة أرقام لتفعيل حسابك.", email: "البريد الإلكتروني", code: "رمز التحقق", submit: "تأكيد الحساب", loading: "جارٍ التحقق…", success: "تم تأكيد البريد، ويمكنك الآن تسجيل الدخول.", failed: "تعذر قبول رمز التحقق.", resend: "إرسال رمز جديد", resendFailed: "تعذر إعادة إرسال الرمز." },
    reset: { eyebrow: "إعادة تعيين آمنة", title: "اختر كلمة مرور جديدة.", description: "استخدم ثمانية أحرف على الأقل وكلمة خاصة بهذا الحساب.", password: "كلمة المرور الجديدة", confirm: "تأكيد كلمة المرور", submit: "تحديث كلمة المرور", loading: "جارٍ التحديث…", mismatch: "كلمتا المرور غير متطابقتين.", missingToken: "رابط الاستعادة لا يحتوي رمز الأمان.", failed: "تعذر تحديث كلمة المرور." },
    landing: { features: "المميزات", how: "كيف يعمل", eyebrow: "جامعتك متزامنة أخيرًا", title1: "اعرف ما يهم.", title2: "قبل أن يفوتك.", subtitle: "يجمع CampusPulse المواعيد والفعاليات والإعلانات والفرص ويحولها إلى خطة يومية شخصية.", start: "ابدأ الآن", meet: "شاهد كيف يعمل", proof1: "تقويم موحد", proof2: "مرافق جامعي", proof3: "مواعيد فائتة", friday: "الجمعة، 29 أغسطس", morning: "صباح الخير، آينا.", daily: "ملخصك اليومي", three: "ثلاثة أمور تحتاج انتباهك اليوم.", review: "مراجعة", today: "اليوم", viewAll: "عرض الكل", ethics: "مهمة أخلاقيات الذكاء الاصطناعي", due: "تستحق خلال ساعتين", workshop: "ورشة النادي التقني", lab: "مختبر FCI XR", briefing: "جلسة تعريف بالمنحة", online: "جلسة عبر الإنترنت", insight: "ملاحظة ذكية", conflict: "وجدت تعارضًا في الجدول.", conflictText: "ورشتك تتعارض مع اجتماع مشروع. راجع تقويمك لاختيار وقت أفضل.", fix: "مراجعة الجدول", opportunity: "فرصة جديدة:", opportunityText: "طلبات منحة Yayasan تغلق يوم الاثنين.", featureKicker: "جامعة واحدة. رؤية واضحة.", featureTitle: "كل ما يجمعه،", featureAccent: "وكل ما يوضحه.", featureText: "ميزات مركزة وفوائد واضحة وطريق مباشر إلى المنتج.", f1Title: "تقويم ذكي واحد", f1Text: "المواعيد والفعاليات والفرص في خط زمني واحد مع كشف التعارضات.", f2Title: "شخصي بلا ضوضاء", f2Text: "ترتب التحديثات حسب اهتماماتك والأولوية.", f3Title: "خطوات تالية واضحة", f3Text: "قارن الأولويات وانتقل مباشرة لما يحتاج انتباهك.", storyKicker: "كيف يعمل CAMPUSPULSE", storyTitle1: "من تحديثات متفرقة", storyTitle2: "إلى خطوة تالية مفيدة.", gather: "اجمع", gatherText: "اجمع الإعلانات والفعاليات والأندية والمنح في موجز واحد.", understand: "افهم", understandText: "طابق كل بند مع اهتمامات الطالب وتقويمه.", act: "تحرك", actText: "وضح الأولويات وجهز خطوات تالية واضحة.", sources: "أنواع مصادر جامعية", timeline: "خط زمني موحد", available: "متاح دائمًا", controlled: "إجراءات يتحكم بها الطالب", finalKicker: "جامعتك تتحرك بالفعل", finalTitle: "تحرك معها.", finalText: "افتح CampusPulse واختبر الملخص اليومي والاستكشاف والتقويم والإشعارات.", enter: "دخول CampusPulse", footer: "صُمم ليوم MMU للابتكار 2026 · نموذج واجهة" },
    dashboard: { kicker: "الجمعة · 29 أغسطس 2026", greeting: "صباح الخير، آينا.", subtitle: "هذا أوضح مسار ليومك الجامعي.", viewCalendar: "عرض التقويم", daily: "الملخص اليومي", dailyTitle: "ثلاثة أمور تحتاج انتباهك اليوم.", dailyText: "تسليم أخلاقيات الذكاء الاصطناعي عند الظهر، ويوجد تعارض واحد ومنحة تغلق خلال ثلاثة أيام.", review: "مراجعة الجدول", deadlines: "المواعيد القادمة", deadlinesNote: "موعدان هذا الأسبوع", events: "فعاليات مناسبة لك", eventsNote: "3 مطابقات جديدة", saved: "الفرص المحفوظة", savedNote: "فرصة تغلق قريبًا", today: "اليوم", agenda: "جدولك", fullCalendar: "التقويم الكامل", rest: "بقية يومك", next: "التالي", focus: "وقت التركيز", until: "حتى الموعد النهائي", assignment: "مهمة أخلاقيات الذكاء الاصطناعي", progress: "TDS 2111 · مكتمل 80%", openAssignment: "فتح المهمة", personal: "مخصص لك", attention: "يستحق اهتمامك", explore: "استكشف الكل", source: "المصدر:", details: "عرض التفاصيل", save: "حفظ", remove: "إزالة" },
    status: { kicker: "حالة الطالب", title: "نظرة سريعة", attendance: "الحضور", grades: "الدرجات", level: "المستوى الحالي", levelValue: "السنة الثانية", deadlines: "المواعيد", risk: "مقرر واحد يحتاج إجراءً فوريًا للحضور" },
    attendance: {
      kicker: "متابعة واضحة للحضور", title: "الحضور", subtitle: "كل غياب يخصم 7.14% من نسبة حضور المقرر.", submitExcuse: "تقديم عذر طبي", overall: "الحضور الإجمالي", courseCount: "عبر {{count}} مقررات نشطة", updated: "عبر 5 مقررات نشطة", deduction: "تُخصم عن كل محاضرة فائتة", barCourses: "مقررات تحت حد 70%", monitoring: "متابعة المقررات", byCourse: "الحضور حسب المقرر", threshold: "أقل من 70% يدخل مرحلة الحرمان", attendance: "الحضور", absences: "مرات غياب", contactStaff: "تواصل مع مسؤولي الكلية", attended: "حضرت", missed: "غبت", marking: "جارٍ الحفظ…",
      courses: { c1: "أخلاقيات الذكاء الاصطناعي", c2: "أنظمة قواعد البيانات", c3: "هندسة البرمجيات", c4: "التفاعل بين الإنسان والحاسوب", c5: "اتصالات البيانات" },
      level: { good: "وضع سليم", notice: "التنبيه الأول", warning: "التحذير الثاني", elevated: "التحذير الثالث", critical: "التحذير النهائي", barred: "مرحلة الحرمان" },
      message: { good: "نسبة حضورك جيدة.", notice: "تغيبت عن محاضرة واحدة وتم إرسال تذكير ذكي.", warning: "تم تسجيل الغياب الثاني، وأصبح التحذير باللون الأصفر.", elevated: "تم تسجيل الغياب الثالث، ويُنصح بتحسين الحضور فورًا.", critical: "تم تسجيل الغياب الرابع ونسبتك قريبة من حد الحرمان.", barred: "نسبة حضورك أقل من 70%. راجع مسؤولي الكلية والدكتور وقدّم الأعذار الطبية للمراجعة." },
    },
    discover: { alt: "طلاب داخل حرم جامعي رقمي", kicker: "استكشف جامعتك", title1: "فرص تناسب", title2: "المكان الذي تتجه إليه.", subtitle: "فعاليات ومنح وأندية ودعم أكاديمي حسب اهتماماتك.", search: "ابحث في فرص الجامعة", all: "الكل", academic: "أكاديمي", event: "فعالية", scholarship: "منحة", club: "نادي", feed: "مختار لك", matches: "{{count}} نتائج مناسبة لك", updated: "محدث من 12 مصدرًا جامعيًا", open: "فتح", empty: "لا توجد نتائج بعد", emptyText: "جرّب عبارة أو فئة مختلفة." },
    calendar: { kicker: "وقتك في مكان واحد", title: "التقويم", subtitle: "المواعيد الأكاديمية والحياة الجامعية بلا تعارض.", add: "إضافة بند شخصي", ready: "البند الشخصي جاهز.", readyText: "يحتفظ به هذا النموذج خلال الجلسة الحالية.", range: "24–30 أغسطس 2026", week: "أسبوع", month: "شهر", today: "اليوم", previous: "الفترة السابقة", next: "الفترة التالية", noEvents: "لا توجد أحداث", showMore: "+{{count}} أخرى", showLess: "عرض أقل", submittedKicker: "الأعمال المكتملة", submitted: "تم التسليم", submittedHint: "تُزال المواعيد المكتملة من التقويم النشط وتُحفظ هنا.", mon: "الاثنين", tue: "الثلاثاء", wed: "الأربعاء", thu: "الخميس", fri: "الجمعة", sat: "السبت", sun: "الأحد", entryCount: "{{count}} بنود", items: "3 بنود", event: "فعالية واحدة", insight: "ملاحظة ذكية", insightTitle: "أكثر أوقاتك ازدحامًا الجمعة من 12 إلى 3 م.", insightText: "يمكن نقل اجتماع المشروع المرن لتوفير 45 دقيقة تركيز قبل الورشة.", resolve: "حل التعارض" },
    notifications: { kicker: "ابقَ متقدمًا بلا ضغط", title: "الإشعارات", subtitle: "فقط التغييرات التي تستحق انتباهك.", mark: "تحديد الكل كمقروء", emailBrief: "أرسل الملخص لبريدي", emailSending: "جارٍ الإرسال…", emailSent: "أُرسل الملخص إلى {{email}} ({{count}} بنود).", emailEmpty: "أُرسل الملخص إلى {{email}} — لا يوجد جديد حالياً.", emailFailed: "تعذر إرسال الملخص.", all: "الكل", unread: "غير مقروء", count: "{{count}} غير مقروء", empty: "اطلعت على كل شيء", emptyText: "ستظهر تحديثات الجامعة الجديدة هنا.", n1Title: "تم تقديم الموعد النهائي", n1Body: "مهمة أخلاقيات الذكاء الاصطناعي تستحق اليوم الساعة 12:00 م.", n1Time: "منذ 8 دقائق", n2Title: "تم العثور على تعارض", n2Body: "ورشة المنتج تتعارض مع اجتماع فريق المشروع.", n2Time: "منذ 24 دقيقة", n3Title: "منحة تغلق قريبًا", n3Body: "طلب منحة Maybank FutureReady يغلق خلال ثلاثة أيام.", n3Time: "منذ ساعة", n4Title: "فعالية جديدة لك", n4Body: "لقاء Gemini للنماذج الأولية يناسب اهتماماتك.", n4Time: "أمس", n5Title: "قبول نادي الروبوتات", n5Body: "التقديم مفتوح لفرق البناء والبرمجيات والتصميم.", n5Time: "أمس", n6Title: "تم تسجيل الغياب الأول", n6Body: "تغيبت عن أخلاقيات الذكاء الاصطناعي وأصبحت نسبة حضورك 92.86%.", n6Time: "منذ 22 دقيقة", n7Title: "تم تسجيل الغياب الثاني", n7Body: "نسبة حضور قواعد البيانات 85.72%. راجع جدولك.", n7Time: "منذ 18 دقيقة", n8Title: "تم تسجيل الغياب الثالث", n8Body: "نسبة حضور هندسة البرمجيات انخفضت إلى 78.58%.", n8Time: "منذ 12 دقيقة", n9Title: "تم تسجيل الغياب الرابع", n9Body: "نسبة حضور التفاعل بين الإنسان والحاسوب 71.44% وتتطلب إجراءً فوريًا.", n9Time: "منذ 5 دقائق", n10Title: "دخلت مرحلة الحرمان", n10Body: "اتصالات البيانات أقل من 70%. راجع مسؤولي الكلية والدكتور وقدّم الأعذار الطبية.", n10Time: "الآن" },
    studyPlan: { kicker: "خطة مذاكرة ذكية", title: "خطط أيامي القادمة", text: "مبنية على مقرراتك ومواعيدك وحضورك.", generate: "ولّد الخطة", loading: "جارٍ بناء خطتك…", failed: "تعذر توليد الخطة. حاول مجدداً.", empty: "لا توجد مهام للتخطيط بعد.", minutes: "{{count}} دقيقة" },
    mmu: { kicker: "خدمات MMU", title: "بوابات جامعتك", subtitle: "الأنظمة الأربعة اللي دراستك قايمة عليها — بضغطة واحدة.", open: "افتح البوابة", external: "تُفتح في تبويب جديد", mainName: "موقع MMU الرسمي", mainText: "الواجهة العامة للجامعة: الكليات، الأخبار، التقويم الأكاديمي، القبول وإعلانات الحرم.", mainTags: "الكليات|الأخبار|القبول", clicName: "منصة CLiC للطلاب", clicText: "سجلك الطلابي: نسبة الحضور لكل مقرر، كشف الرسوم ودفعها، وتسجيل المواد كل فصل.", clicTags: "الحضور|الرسوم|تسجيل المواد", ebwiseName: "منصة eBWise", ebwiseText: "محتوى المقررات: مواد المحاضرات، وصف الواجبات، تسليم اللابات، الكوزات والميد تيرم.", ebwiseTags: "الواجبات|اللابات|الاختبارات", teamsName: "Microsoft Teams", teamsText: "المحاضرات المباشرة والمسجلة، جلسات التيوتوريال، والواجبات اللي بعض الدكاترة يستلمونها عبر Teams.", teamsTags: "المحاضرات|الاجتماعات|الملفات" },
    messages: { kicker: "كل القنوات في صندوق واحد", title: "الرسائل", subtitle: "Teams وOutlook وBlackboard وMoodle في مكان واحد.", all: "الكل", unread: "غير المقروء", count: "{{count}} غير مقروء", progress: "التقدم", done: "مكتمل", markRead: "تحديد كمقروء", dismiss: "إخفاء", empty: "لا توجد رسائل بعد", emptyText: "ستصل رسائل قنوات الجامعة هنا بعد توليد خلاصتك.", track: "تتبع هذا", tracking: "قيد المتابعة" },
    profile: { kicker: "خصص تجربتك", title: "ملفك الشخصي", subtitle: "هذه التفاصيل تحدد ما يعرضه CampusPulse.", saved: "حُفظ ملفك وأُعيد توليد الخلاصة.", campus: "الحرم", campusValue: "سايبرجايا", year: "السنة الدراسية", yearValue: "السنة الثانية", preferences: "تفضيلات الاستكشاف", interests: "اهتماماتك", interestsText: "اختر الموضوعات لضبط التوصيات.", save: "حفظ التفضيلات", academicKicker: "الملف الأكاديمي", academicTitle: "المقررات والبيانات الأكاديمية", academicText: "التخصيص يطابق مستجدات الجامعة مع هذه البيانات. اختر مقرراً واحداً على الأقل واهتماماً واحداً.", faculty: "الكلية", major: "التخصص", yearOfStudy: "سنة الدراسة", coursesLabel: "مقرراتي", otherFaculty: "مقررات أخرى", saveGenerate: "حفظ وتوليد الخلاصة", generating: "جارٍ توليد الخلاصة…", requireBoth: "اختر مقرراً واحداً على الأقل واهتماماً واحداً قبل الحفظ.", noCourses: "كتالوج المقررات فارغ — اهتماماتك وحدها هي اللي بتحرك التخصيص حالياً.", coursesFailed: "تعذر تحميل كتالوج المقررات. تقدر تحفظ الباقي.", requireInterest: "اختر اهتماماً واحداً على الأقل قبل الحفظ.", onboarding: "أكمل هذه الخطوة مرة واحدة حتى يتمكن CampusPulse من تخصيص خلاصتك.", ai: "الذكاء الاصطناعي", design: "تصميم المنتجات", scholarships: "المنح", hackathons: "الهاكاثونات", entrepreneurship: "ريادة الأعمال", sustainability: "الاستدامة", robotics: "الروبوتات", volunteering: "التطوع" },
    data: {
      i1: { title: "مهمة أخلاقيات الذكاء الاصطناعي", date: "29 أغسطس", location: "بوابة تسليم MMLS", description: "تأمل نهائي وتحليل حالة للذكاء الاصطناعي المسؤول.", source: "TDS 2111 · إعلان المقرر" },
      i2: { title: "ورشة منتجات النادي التقني", date: "29 أغسطس", location: "مختبر FCI XR", description: "ورشة نماذج أولية سريعة للطلاب المطورين.", source: "جمعية تقنية المعلومات · إعلان فعالية" },
      i3: { title: "جلسة تعريف بمنحة Yayasan", date: "29 أغسطس", location: "Microsoft Teams", description: "شرح الأهلية والمستندات وخطوات التقديم.", source: "شؤون الطلاب · مكتب المنح" },
      i4: { title: "تحدي استدامة الحرم", date: "30 أغسطس", location: "ردهة CLC", description: "قدّم أفكارًا عملية لحرم MMU أكثر استدامة.", source: "مكتب الاستدامة" },
      i5: { title: "اختبار أنظمة قواعد البيانات", date: "31 أغسطس", location: "اختبار MMLS عبر الإنترنت", description: "يشمل التطبيع والمعاملات والفهرسة.", source: "TDB 2201 · إعلان المقرر" },
      i11: { title: "منحة Maybank FutureReady", date: "تغلق 1 سبتمبر", location: "تقديم عبر الإنترنت", description: "تمويل وإرشاد لطلاب الجامعات الماليزيين النشطين مجتمعيًا.", source: "شؤون طلاب MMU" },
      i12: { title: "لقاء Google Developer Groups الجامعي", date: "3 سبتمبر", location: "قاعة محاضرات FCI 2", description: "عروض سريعة وتواصل وتجربة Gemini العملية مع مطوري الطلاب.", source: "GDG في حرم MMU" },
      i13: { title: "قبول نادي الروبوتات 2026", date: "5 سبتمبر", location: "مختبر الهندسة والتصنيع", description: "انضم إلى فريق البناء أو البرمجيات أو التصميم. المبتدئون مرحب بهم.", source: "نادي روبوتات MMU" },
      i14: { title: "عيادة الكتابة الأكاديمية", date: "6 سبتمبر", location: "نقطة التعلم، المكتبة", description: "أحضر مسودة واحصل على ملاحظات فردية حول البنية والمراجع.", source: "مكتبة MMU" },
    },
    legal: { back: "العودة لإنشاء الحساب", effective: "ساري من 29 أغسطس 2026", termsKicker: "الشؤون القانونية", termsTitle: "شروط الاستخدام", termsIntro: "توضح هذه الشروط استخدام خدمة CampusPulse لمشروع يوم الابتكار. بإنشاء حساب أو استخدام الخدمة فإنك توافق عليها.", t1: "1. حالة الخدمة", tp1: "CampusPulse مشروع ليوم MMU للابتكار وليس خدمة رسمية، ولا ينبغي الاعتماد عليه وحده للمعلومات الجامعية المهمة.", t2: "2. حسابك", tp2: "تدار جلستك الموثقة عبر واجهة CampusPulse الخلفية المضبوطة. أنت مسؤول عن صحة معلوماتك وتأمين جهازك.", t3: "3. الاستخدام المقبول", tp3: "استخدم CampusPulse للأغراض الطلابية والقانونية فقط، ولا تعطل الخدمة أو تنتحل شخصية غيرك.", t4: "4. دقة المعلومات", tp4: "قد تتضمن المعلومات بيانات تجريبية أو متزامنة. تأكد من السجلات والتواريخ المهمة عبر قنوات MMU الرسمية.", t5: "5. التغييرات", tp5: "قد تتغير الخدمة وهذه الشروط مع تطور المشروع.", termsCallout: "يمكن توجيه الأسئلة إلى فريق CampusPulse في يوم الابتكار.", privacyKicker: "بياناتك بوضوح", privacyTitle: "سياسة الخصوصية", privacyIntro: "توضح هذه السياسة كيف يتعامل CampusPulse مع المعلومات التي تدخلها والبيانات التي تعيدها الواجهة الخلفية.", p1: "1. ما الذي يُعالج", pp1: "قد يعالج CampusPulse اسمك وبريدك وعنوانك وملفك الأكاديمي وتفضيلاتك وحالة الجلسة والمعلومات الجامعية ذات الصلة.", p2: "2. أين تذهب المعلومات", pp2: "عند توفر الواجهة الخلفية، تُرسل بيانات الحساب والملف إلى خادم CampusPulse المضبوط. قد يحتفظ وضع التطوير ببيانات عرض محدودة على جهازك عند انقطاع الخادم.", p3: "3. كيفية الاستخدام", pp3: "تُستخدم المعلومات لمصادقتك وتخصيص التحديثات وعرض لوحة الطالب.", p4: "4. المشاركة والبيع", pp4: "لا يبيع CampusPulse معلوماتك ولا يشاركها مع المعلنين. قد توفر خدمات جامعية مخولة البيانات اللازمة للمنتج.", p5: "5. اختياراتك", pp5: "يمكنك تسجيل الخروج وحذف بيانات الموقع المحلية والتواصل مع الفريق بشأن بيانات حسابك.", p6: "6. تكاملات الخدمة", pp6: "يجب أن تتبع تكاملات الخادم ومصادر الجامعة والذكاء الاصطناعي متطلبات البيانات والأمان والموافقة قبل الإنتاج.", privacyCallout: "يمكن توجيه أسئلة الخصوصية إلى فريق CampusPulse في يوم الابتكار." },
  },
  ms: {
    common: { language: "Bahasa", brandSubtitle: "Hab pelajar MMU", signIn: "Log masuk", signOut: "Log keluar", dismiss: "Tutup", loading: "Memuatkan…" },
    nav: { label: "Halaman CampusPulse", campus: "KAMPUS SAYA", home: "Utama", discover: "Semua kemas kini", attendance: "Kehadiran", calendar: "Kalendar", notifications: "Notifikasi", settings: "Tetapan", open: "Buka navigasi", close: "Tutup navigasi", messages: "Mesej", closeOverlay: "Tutup lapisan navigasi", mmu: "MMU", mmuHint: "Membuka laman web MMU dalam tab baharu" },
    roles: { student: "Pelajar", academicProfile: "Profil akademik", studentAcademy: "Sarjana Muda Sains Komputer", autoAssigned: "Ditugaskan automatik" },
    topbar: { searchLabel: "Cari CampusPulse", search: "Cari tarikh akhir, acara, kelab…", synced: "Sumber kampus disegerakkan", notifications: "Lihat notifikasi" },
    authVisual: { alt: "Pelajar di kampus yang saling berhubung", badge: "Satu kampus. Satu pandangan jelas.", title1: "Ketahui yang penting.", title2: "Sebelum terlepas.", description: "Tarikh akhir, acara dan peluang anda—disusun untuk anda.", deadline: "TARIKH AKHIR SETERUSNYA", deadlineValue: "Etika AI · 12:00 PTG", match: "PADANAN BAHARU", matchValue: "Biasiswa ditutup Isnin", footer: "© 2026 CampusPulse · MMU Hack Day" },
    login: { eyebrow: "SELAMAT KEMBALI", title: "Log masuk ke kampus anda.", description: "Teruskan ke ruang CampusPulse peribadi anda.", email: "Alamat e-mel", emailPlaceholder: "name@example.com", password: "Kata laluan", keep: "Kekalkan saya log masuk", forgot: "Lupa kata laluan?", submit: "Log masuk", loading: "Sedang log masuk…", newAccount: "Baharu di CampusPulse?", create: "Cipta akaun anda", secure: "Sesi anda dilindungi oleh kuki pelayan yang selamat.", error: "Masukkan e-mel yang sah dan kata laluan sekurang-kurangnya 6 aksara.", failed: "Log masuk gagal. Semak butiran dan cuba lagi.", show: "Tunjukkan kata laluan", hide: "Sembunyikan kata laluan" },
    signup: { eyebrow: "CIPTA RUANG ANDA", title: "Jadikan kampus lebih peribadi.", description: "Sediakan profil dan tentukan apa yang CampusPulse paparkan.", first: "Nama pertama", last: "Nama keluarga", email: "Alamat e-mel", emailPlaceholder: "name@example.com", address: "Alamat", addressPlaceholder: "Alamat jalan", password: "Kata laluan", passwordPlaceholder: "Sekurang-kurangnya 8 aksara", agree: "Saya bersetuju dengan", terms: "Terma", and: "dan", privacy: "Dasar Privasi", submit: "Cipta akaun", loading: "Mencipta akaun…", failed: "Akaun tidak dapat dicipta.", existing: "Sudah mempunyai akaun?", signIn: "Log masuk" },
    recovery: { eyebrow: "PEMULIHAN AKAUN", title: "Tetapkan semula kata laluan.", description: "Masukkan e-mel dan kami akan menghantar pautan pemulihan selamat.", email: "Alamat e-mel", emailPlaceholder: "name@example.com", continue: "Hantar pautan", loading: "Menghantar…", failed: "E-mel pemulihan tidak dapat dihantar.", back: "Kembali ke log masuk", success: "Semak peti masuk", prepared: "Pautan pemulihan dihantar kepada {{email}}." },
    verify: { eyebrow: "SAHKAN E-MEL", title: "Masukkan kod pengesahan.", description: "Gunakan kod enam digit yang dihantar untuk mengaktifkan akaun.", email: "Alamat e-mel", code: "Kod pengesahan", submit: "Sahkan akaun", loading: "Mengesahkan…", success: "E-mel disahkan. Anda boleh log masuk.", failed: "Kod pengesahan tidak dapat diterima.", resend: "Hantar kod baharu", resendFailed: "Kod tidak dapat dihantar semula." },
    reset: { eyebrow: "TETAP SEMULA SELAMAT", title: "Pilih kata laluan baharu.", description: "Gunakan sekurang-kurangnya lapan aksara dan pastikan ia unik.", password: "Kata laluan baharu", confirm: "Sahkan kata laluan", submit: "Kemas kini kata laluan", loading: "Mengemas kini…", mismatch: "Kata laluan tidak sepadan.", missingToken: "Pautan ini tiada token keselamatan.", failed: "Kata laluan tidak dapat dikemas kini." },
    landing: { features: "Ciri-ciri", how: "Cara ia berfungsi", eyebrow: "Kampus anda akhirnya selaras", title1: "Ketahui yang penting.", title2: "Sebelum terlepas.", subtitle: "CampusPulse mengumpulkan tarikh akhir, acara, pengumuman dan peluang lalu menjadikannya satu rancangan harian peribadi.", start: "Mulakan", meet: "Lihat cara ia berfungsi", proof1: "kalendar bersepadu", proof2: "rakan kampus", proof3: "tarikh akhir terlepas", friday: "Jumaat, 29 Ogos", morning: "Selamat pagi, Aina.", daily: "PULSE HARIAN ANDA", three: "Tiga perkara memerlukan perhatian anda hari ini.", review: "Semak", today: "Hari ini", viewAll: "Lihat semua", ethics: "Tugasan Etika AI", due: "Perlu dihantar dalam 2 jam", workshop: "Bengkel Kelab Teknologi", lab: "Makmal FCI XR", briefing: "Taklimat biasiswa", online: "Sesi dalam talian", insight: "PANDANGAN PINTAR", conflict: "Saya menemui konflik jadual.", conflictText: "Bengkel anda bertindih dengan mesyuarat projek. Semak kalendar untuk masa yang lebih sesuai.", fix: "Semak jadual", opportunity: "Peluang baharu:", opportunityText: "Permohonan biasiswa Yayasan ditutup Isnin.", featureKicker: "SATU KAMPUS. SATU PANDANGAN JELAS.", featureTitle: "Semua yang dikumpulkan,", featureAccent: "dan semua yang diperjelas.", featureText: "Ciri fokus, manfaat nyata dan laluan terus ke produk.", f1Title: "Satu kalendar pintar", f1Text: "Tarikh akhir, acara kelab dan peluang berkongsi satu garis masa dengan pengesanan konflik.", f2Title: "Peribadi, bukan bising", f2Text: "Kemas kini disusun mengikut minat dan keutamaan anda.", f3Title: "Langkah seterusnya yang jelas", f3Text: "Bandingkan keutamaan dan pergi terus ke perkara yang memerlukan perhatian.", storyKicker: "CARA CAMPUSPULSE BERFUNGSI", storyTitle1: "Daripada kemas kini berselerak", storyTitle2: "kepada satu langkah berguna.", gather: "Kumpul", gatherText: "Bawa notis, acara, kelab dan biasiswa ke satu suapan.", understand: "Fahami", understandText: "Padankan setiap item dengan minat dan kalendar pelajar.", act: "Bertindak", actText: "Jelaskan keutamaan dan sediakan langkah seterusnya.", sources: "jenis sumber kampus", timeline: "garis masa pelajar bersepadu", available: "sentiasa tersedia", controlled: "tindakan dikawal pelajar", finalKicker: "KAMPUS ANDA SUDAH BERGERAK", finalTitle: "Bergerak bersamanya.", finalText: "Buka CampusPulse dan alami ringkasan harian, suapan penemuan, kalendar dan notifikasi.", enter: "Masuk CampusPulse", footer: "Direka untuk MMU Hack Day 2026 · Demo frontend" },
    dashboard: { kicker: "JUMAAT · 29 OGOS 2026", greeting: "Selamat pagi, Aina.", subtitle: "Inilah laluan paling jelas untuk hari kampus anda.", viewCalendar: "Lihat kalendar", daily: "RINGKASAN HARIAN", dailyTitle: "Tiga perkara memerlukan perhatian anda hari ini.", dailyText: "Tugasan Etika AI perlu dihantar tengah hari. Terdapat juga satu konflik jadual dan biasiswa yang ditutup dalam tiga hari.", review: "Semak jadual", deadlines: "Tarikh akhir akan datang", deadlinesNote: "2 minggu ini", events: "Acara untuk anda", eventsNote: "3 padanan baharu", saved: "Peluang disimpan", savedNote: "1 ditutup tidak lama lagi", today: "HARI INI", agenda: "Agenda anda", fullCalendar: "Kalendar penuh", rest: "Lihat baki hari anda", next: "SETERUSNYA", focus: "Waktu fokus", until: "hingga tarikh akhir", assignment: "Tugasan Etika AI", progress: "TDS 2111 · 80% selesai", openAssignment: "Buka tugasan", personal: "UNTUK ANDA", attention: "Wajar diberi perhatian", explore: "Teroka semua", source: "Sumber:", details: "Lihat butiran", save: "Simpan", remove: "Buang" },
    status: { kicker: "STATUS PELAJAR", title: "Sepintas lalu", attendance: "Kehadiran", grades: "Gred", level: "Tahap semasa", levelValue: "Tahun 2", deadlines: "Tarikh akhir", risk: "Satu kursus memerlukan tindakan kehadiran segera" },
    attendance: {
      kicker: "KEHADIRAN YANG JELAS", title: "Kehadiran", subtitle: "Setiap ketidakhadiran mengurangkan 7.14% daripada peratus kursus.", submitExcuse: "Hantar alasan perubatan", overall: "Kehadiran keseluruhan", courseCount: "Merentas {{count}} kursus aktif", updated: "Merentas 5 kursus aktif", deduction: "ditolak bagi setiap kelas yang tidak dihadiri", barCourses: "kursus di bawah ambang 70%", monitoring: "PEMANTAUAN KURSUS", byCourse: "Kehadiran mengikut kursus", threshold: "Bawah 70% memasuki sekatan kehadiran", attendance: "Kehadiran", absences: "ketidakhadiran", contactStaff: "Hubungi staf fakulti", attended: "Hadir", missed: "Tidak hadir", marking: "Menyimpan…",
      courses: { c1: "Etika AI", c2: "Sistem Pangkalan Data", c3: "Kejuruteraan Perisian", c4: "Interaksi Manusia–Komputer", c5: "Komunikasi Data" },
      level: { good: "Baik", notice: "Notis pertama", warning: "Amaran kedua", elevated: "Amaran ketiga", critical: "Amaran akhir", barred: "Sekatan kehadiran" },
      message: { good: "Kehadiran anda sihat.", notice: "Anda terlepas satu kelas. Peringatan pintar telah dihantar.", warning: "Ketidakhadiran kedua direkodkan. Amaran kini berwarna kuning.", elevated: "Ketidakhadiran ketiga direkodkan. Penambahbaikan segera disyorkan.", critical: "Ketidakhadiran keempat direkodkan. Kehadiran hampir ke ambang sekatan.", barred: "Kehadiran anda di bawah 70%. Lawati staf fakulti dan pensyarah serta serahkan alasan perubatan untuk semakan." },
    },
    discover: { alt: "Pelajar bergerak melalui kampus digital", kicker: "TEROKA KAMPUS ANDA", title1: "Peluang yang sesuai", title2: "dengan hala tuju anda.", subtitle: "Acara, biasiswa, kelab dan sokongan akademik mengikut minat anda.", search: "Cari peluang kampus", all: "Semua", academic: "Akademik", event: "Acara", scholarship: "Biasiswa", club: "Kelab", feed: "SENARAI PILIHAN", matches: "{{count}} padanan untuk anda", updated: "Dikemas kini daripada 12 sumber kampus", open: "Buka", empty: "Belum ada padanan", emptyText: "Cuba frasa atau kategori lain." },
    calendar: { kicker: "MASA ANDA DI SATU TEMPAT", title: "Kalendar", subtitle: "Tarikh akhir akademik dan kehidupan kampus tanpa pertembungan.", add: "Tambah item peribadi", ready: "Item peribadi sedia.", readyText: "Demo frontend menyimpannya untuk sesi semasa.", range: "24–30 Ogos 2026", week: "Minggu", month: "Bulan", today: "Hari ini", previous: "Tempoh sebelumnya", next: "Tempoh seterusnya", noEvents: "Tiada acara", showMore: "+{{count}} lagi", showLess: "Tunjuk kurang", submittedKicker: "KERJA SELESAI", submitted: "Telah dihantar", submittedHint: "Tarikh akhir yang selesai dikeluarkan daripada kalendar aktif dan disimpan di sini.", mon: "Isn", tue: "Sel", wed: "Rab", thu: "Kha", fri: "Jum", sat: "Sab", sun: "Aha", entryCount: "{{count}} item", items: "3 item", event: "1 acara", insight: "PANDANGAN PULSE", insightTitle: "Waktu paling sibuk ialah Jumaat, 12–3 PTG.", insightText: "Daftar masuk projek fleksibel boleh dipindah supaya anda mempunyai 45 minit fokus sebelum bengkel.", resolve: "Selesaikan konflik" },
    notifications: { kicker: "KEKAL DI HADAPAN, TANPA TERBEBAN", title: "Notifikasi", subtitle: "Hanya perubahan yang memerlukan perhatian anda.", mark: "Tandakan semua dibaca", emailBrief: "E-melkan ringkasan saya", emailSending: "Menghantar…", emailSent: "Ringkasan dihantar ke {{email}} ({{count}} item).", emailEmpty: "Ringkasan dihantar ke {{email}} — tiada apa-apa aktif.", emailFailed: "Kami tidak dapat menghantar ringkasan anda.", all: "Semua", unread: "Belum dibaca", count: "{{count}} belum dibaca", empty: "Semuanya telah dibaca", emptyText: "Kemas kini kampus baharu akan muncul di sini.", n1Title: "Tarikh akhir diawalkan", n1Body: "Tugasan Etika AI kini perlu dihantar hari ini pada 12:00 PTG.", n1Time: "8 min lalu", n2Title: "Pulse menemui konflik", n2Body: "Bengkel produk bertindih dengan daftar masuk pasukan projek.", n2Time: "24 min lalu", n3Title: "Biasiswa ditutup tidak lama lagi", n3Body: "Permohonan Maybank FutureReady ditutup dalam tiga hari.", n3Time: "1 jam lalu", n4Title: "Acara baharu untuk anda", n4Body: "Pertemuan prototaip Gemini sepadan dengan minat anda.", n4Time: "Semalam", n5Title: "Pengambilan Kelab Robotik", n5Body: "Permohonan dibuka untuk pasukan binaan, perisian dan reka bentuk.", n5Time: "Semalam", n6Title: "Ketidakhadiran pertama direkodkan", n6Body: "Anda terlepas Etika AI. Kehadiran kini 92.86%.", n6Time: "22 min lalu", n7Title: "Ketidakhadiran kedua direkodkan", n7Body: "Kehadiran Sistem Pangkalan Data kini 85.72%.", n7Time: "18 min lalu", n8Title: "Ketidakhadiran ketiga direkodkan", n8Body: "Kehadiran Kejuruteraan Perisian turun kepada 78.58%.", n8Time: "12 min lalu", n9Title: "Ketidakhadiran keempat direkodkan", n9Body: "Kehadiran Interaksi Manusia–Komputer kini 71.44% dan memerlukan tindakan segera.", n9Time: "5 min lalu", n10Title: "Sekatan kehadiran dicapai", n10Body: "Komunikasi Data di bawah 70%. Lawati staf fakulti dan pensyarah dengan alasan perubatan.", n10Time: "Baru sahaja" },
    studyPlan: { kicker: "PELAN BELAJAR AI", title: "Rancang beberapa hari akan datang", text: "Dibina daripada kursus, tarikh akhir dan kehadiran anda.", generate: "Jana pelan", loading: "Membina pelan anda…", failed: "Pelan tidak dapat dijana. Cuba lagi.", empty: "Tiada tugasan untuk dirancang.", minutes: "{{count}} min" },
    mmu: { kicker: "PERKHIDMATAN MMU", title: "Portal universiti anda", subtitle: "Empat sistem yang menjalankan pengajian anda — satu sentuhan sahaja.", open: "Buka portal", external: "Dibuka dalam tab baharu", mainName: "Laman Rasmi MMU", mainText: "Laman awam universiti: fakulti, berita, kalendar akademik, kemasukan dan pengumuman kampus.", mainTags: "Fakulti|Berita|Kemasukan", clicName: "Portal Pelajar CLiC", clicText: "Rekod pelajar anda: peratus kehadiran setiap subjek, penyata dan pembayaran yuran, serta pendaftaran kursus.", clicTags: "Kehadiran|Yuran|Pendaftaran", ebwiseName: "Pembelajaran eBWise", ebwiseText: "Penyampaian kursus: bahan kuliah, tugasan, penghantaran lab, kuiz dan peperiksaan pertengahan.", ebwiseTags: "Tugasan|Lab|Kuiz", teamsName: "Microsoft Teams", teamsText: "Kuliah langsung dan rakaman, sesi tutorial, dan tugasan yang dikumpul melalui Teams.", teamsTags: "Kuliah|Mesyuarat|Fail" },
    messages: { kicker: "SETIAP SALURAN, SATU PETI MASUK", title: "Mesej", subtitle: "Teams, Outlook, Blackboard dan Moodle di satu tempat.", all: "Semua", unread: "Belum dibaca", count: "{{count}} belum dibaca", progress: "Kemajuan", done: "Selesai", markRead: "Tandakan dibaca", dismiss: "Sembunyikan", empty: "Tiada mesej lagi", emptyText: "Saluran kampus akan sampai di sini selepas suapan anda dijana.", track: "Jejak ini", tracking: "Sedang dijejak" },
    profile: { kicker: "PERIBADIKAN PULSE ANDA", title: "Profil anda", subtitle: "Butiran ini menentukan apa yang CampusPulse paparkan.", saved: "Profil disimpan. Suapan anda dijana semula.", campus: "Kampus", campusValue: "Cyberjaya", year: "Tahun pengajian", yearValue: "Tahun 2", preferences: "KEUTAMAAN PENEMUAN", interests: "Minat anda", interestsText: "Pilih topik untuk menyesuaikan cadangan.", save: "Simpan keutamaan", academicKicker: "PROFIL AKADEMIK", academicTitle: "Kursus dan butiran akademik", academicText: "Pemperibadian memadankan kemas kini kampus dengan butiran ini. Pilih sekurang-kurangnya satu kursus dan satu minat.", faculty: "Fakulti", major: "Jurusan", yearOfStudy: "Tahun pengajian", coursesLabel: "Kursus anda", otherFaculty: "Kursus lain", saveGenerate: "Simpan dan jana suapan", generating: "Menjana suapan anda…", requireBoth: "Pilih sekurang-kurangnya satu kursus dan satu minat sebelum menyimpan.", noCourses: "Katalog kursus kosong — minat anda sahaja yang memacu pemperibadian buat masa ini.", coursesFailed: "Katalog kursus tidak dapat dimuatkan. Anda masih boleh menyimpan yang lain.", requireInterest: "Pilih sekurang-kurangnya satu minat sebelum menyimpan.", onboarding: "Lengkapkan sekali sahaja supaya CampusPulse boleh memperibadikan suapan anda.", ai: "Kecerdasan buatan", design: "Reka bentuk produk", scholarships: "Biasiswa", hackathons: "Hackathon", entrepreneurship: "Keusahawanan", sustainability: "Kelestarian", robotics: "Robotik", volunteering: "Sukarelawan" },
    data: {
      i1: { title: "Tugasan Etika AI", date: "29 Ogos", location: "Portal penyerahan MMLS", description: "Refleksi akhir dan analisis kes AI yang bertanggungjawab.", source: "TDS 2111 · Pengumuman kursus" },
      i2: { title: "Bengkel produk Kelab Teknologi", date: "29 Ogos", location: "Makmal FCI XR", description: "Bengkel prototaip pantas untuk pembina pelajar.", source: "Persatuan IT · Notis acara" },
      i3: { title: "Taklimat biasiswa Yayasan", date: "29 Ogos", location: "Microsoft Teams", description: "Panduan kelayakan, dokumen dan permohonan.", source: "Hal Ehwal Pelajar · Meja biasiswa" },
      i4: { title: "Cabaran kelestarian kampus", date: "30 Ogos", location: "Ruang Legar CLC", description: "Bentangkan idea praktikal untuk kampus MMU yang lebih hijau.", source: "Pejabat Kelestarian" },
      i5: { title: "Kuiz sistem pangkalan data", date: "31 Ogos", location: "Kuiz dalam talian MMLS", description: "Meliputi normalisasi, transaksi dan pengindeksan.", source: "TDB 2201 · Pengumuman kursus" },
      i11: { title: "Biasiswa Maybank FutureReady", date: "Ditutup 1 Sep", location: "Permohonan dalam talian", description: "Pembiayaan dan bimbingan untuk mahasiswa Malaysia yang aktif dalam komuniti.", source: "Hal Ehwal Pelajar MMU" },
      i12: { title: "Pertemuan Kampus Google Developer Groups", date: "3 Sep", location: "Dewan Kuliah FCI 2", description: "Ceramah ringkas, rangkaian dan prototaip Gemini bersama pembangun pelajar.", source: "GDG on Campus MMU" },
      i13: { title: "Pengambilan Kelab Robotik 2026", date: "5 Sep", location: "Makmal Pembuat Kejuruteraan", description: "Sertai pasukan binaan, perisian atau reka bentuk. Pemula dialu-alukan.", source: "Kelab Robotik MMU" },
      i14: { title: "Klinik penulisan akademik", date: "6 Sep", location: "Learning Point, Perpustakaan", description: "Bawa draf dan dapatkan maklum balas individu tentang struktur dan sitasi.", source: "Perpustakaan MMU" },
    },
    legal: { back: "Kembali ke pendaftaran", effective: "Berkuat kuasa 29 Ogos 2026", termsKicker: "UNDANG-UNDANG CAMPUSPULSE", termsTitle: "Terma Penggunaan", termsIntro: "Terma ini menerangkan penggunaan perkhidmatan CampusPulse untuk projek Hack Day. Dengan mencipta akaun atau menggunakan perkhidmatan, anda bersetuju dengannya.", t1: "1. Status perkhidmatan", tp1: "CampusPulse ialah projek MMU Hack Day dan bukan perkhidmatan rasmi. Jangan gunakannya sebagai satu-satunya sumber maklumat penting.", t2: "2. Akaun anda", tp2: "Sesi disahkan melalui API CampusPulse yang dikonfigurasi. Anda bertanggungjawab terhadap ketepatan maklumat dan keselamatan peranti.", t3: "3. Penggunaan yang dibenarkan", tp3: "Gunakan CampusPulse untuk tujuan pelajar yang sah sahaja. Jangan mengganggu atau menyamar.", t4: "4. Ketepatan maklumat", tp4: "Maklumat mungkin sampel atau data terselaras. Sahkan rekod dan tarikh penting melalui saluran rasmi MMU.", t5: "5. Perubahan", tp5: "Perkhidmatan dan terma boleh berubah semasa projek berkembang.", termsCallout: "Soalan boleh diajukan kepada pasukan CampusPulse Hack Day.", privacyKicker: "DATA ANDA, DITERANGKAN DENGAN JELAS", privacyTitle: "Dasar Privasi", privacyIntro: "Dasar ini menerangkan cara CampusPulse mengendalikan maklumat yang anda masukkan dan data daripada API.", p1: "1. Data yang diproses", pp1: "CampusPulse boleh memproses nama, e-mel, alamat, profil akademik, keutamaan, sesi dan maklumat kampus yang berkaitan.", p2: "2. Lokasi maklumat", pp2: "Apabila API tersedia, data akaun dan profil dihantar ke backend CampusPulse. Fallback pembangunan terhad mungkin menyimpan data paparan sesi pada peranti ini apabila pelayan tidak tersedia.", p3: "3. Cara ia digunakan", pp3: "Maklumat digunakan untuk pengesahan, pemperibadian kemas kini dan paparan papan pemuka akademik.", p4: "4. Perkongsian dan penjualan", pp4: "CampusPulse tidak menjual maklumat atau berkongsinya dengan pengiklan. Perkhidmatan kampus yang dibenarkan boleh menyediakan data yang diperlukan.", p5: "5. Pilihan anda", pp5: "Anda boleh log keluar, memadam data laman setempat dan menghubungi pasukan mengenai data akaun.", p6: "6. Integrasi perkhidmatan", pp6: "Integrasi backend, sumber kampus dan AI mesti mematuhi keperluan data, keselamatan dan persetujuan sebelum produksi.", privacyCallout: "Soalan privasi boleh diajukan kepada pasukan CampusPulse Hack Day." },
  },
} as const;

const supplementalTranslations = {
  en: {
    system: { loadFailed: "Could not load this data", retry: "Try again", emptyResponse: "The server returned an empty response." },
    onboarding: { eyebrow: "ACADEMIC ONBOARDING", title: "Tell us what belongs in your feed.", subtitle: "Only courses selected from the university database can be saved.", faculty: "Faculty (optional)", major: "Major (optional)", year: "Year of study (1–10)", interests: "Interests", interestHint: "Choose an interest", selectFaculty: "Select a faculty", selectMajor: "Select a major", selectYear: "Select a year", selectInterest: "Select an interest", add: "Add", search: "Search the course catalog", searchHint: "Code, course name or faculty", selectError: "Choose at least one course and add at least one interest.", yearError: "Year of study must be a whole number from 1 to 10.", save: "Save and personalize", complete: "Complete setup", saving: "Saving academic profile…", building: "Building your CampusPulse…", buildingText: "Your courses are saved. We are preparing your feed, calendar and attendance data.", retryTitle: "Personalization needs another try", retry: "Retry personalization" },
    settings: { kicker: "ACCOUNT PREFERENCES", title: "Settings", subtitle: "Control language, delivery and your academic personalization.", interface: "Interface", language: "Language", timezone: "Timezone", light: "Use light theme", dark: "Use dark theme", delivery: "Notification delivery", frequency: "Frequency", all: "All", important: "Important", critical: "Critical only", preferred: "Preferred time", dailySummary: "Daily summary", deadlineNotifications: "Deadline notifications", courseNotifications: "Course notifications", eventNotifications: "Event notifications", scholarshipNotifications: "Scholarship notifications", academic: "Academic profile", academicText: "Course and interest changes regenerate your personalized feed from the database.", edit: "Edit academic profile", save: "Save changed fields", saving: "Saving…", saved: "Settings saved to your account." },
    live: { unavailable: "Backend unavailable", inbox: "Latest messages", openInbox: "Open inbox", feed: "PERSONALIZED FEED", feedEmpty: "Your feed is empty", feedEmptyText: "No database notifications were returned for this account.", attendanceUnavailable: "Attendance summary unavailable", safeAttendance: "No course is below the 70% attendance threshold", morning: "Good morning", afternoon: "Good afternoon", evening: "Good evening" },
    updates: { api: "Live data from the campus-content API", all: "All", announcements: "Announcements", deadlines: "Deadlines", events: "Events", scholarships: "Scholarships", upcoming: "Upcoming only", allDates: "All dates" },
    why: { action: "Why am I seeing this?", title: "WHY THIS?", loading: "Explaining this message…", unavailable: "Explanation unavailable", none: "No additional factors were returned." },
    legal: { pp2: "Account, academic and preference data is sent only to the configured CampusPulse backend. This frontend does not create a local fallback account or substitute database records.", pp5: "You can sign out and contact the CampusPulse team about the data stored for your account." },
    calendarAction: { kicker: "CALENDAR ACTION", attendance: "Attendance for this lecture", submission: "Submission", markSubmitted: "Mark as submitted", notSubmitted: "Not submitted yet", alreadySubmitted: "Already submitted", notification: "Notification state", alreadyRead: "Already read", markRead: "Mark as read", archived: "Already archived", archive: "Archive after saving", save: "Save changes", saving: "Saving…" },
  },
  ar: {
    system: { loadFailed: "تعذر تحميل هذه البيانات", retry: "حاول مرة أخرى", emptyResponse: "أعاد الخادم استجابة فارغة." },
    onboarding: { eyebrow: "الإعداد الأكاديمي", title: "حدد ما ينتمي إلى خلاصتك.", subtitle: "لا يمكن حفظ إلا المقررات الموجودة في قاعدة بيانات الجامعة.", faculty: "الكلية (اختياري)", major: "التخصص (اختياري)", year: "سنة الدراسة (1–10)", interests: "الاهتمامات", interestHint: "اختر اهتمامًا", selectFaculty: "اختر الكلية", selectMajor: "اختر التخصص", selectYear: "اختر السنة", selectInterest: "اختر الاهتمام", add: "إضافة", search: "ابحث في كتالوج المقررات", searchHint: "رمز المقرر أو اسمه أو الكلية", selectError: "اختر مقررًا واحدًا وأضف اهتمامًا واحدًا على الأقل.", yearError: "يجب أن تكون سنة الدراسة رقمًا صحيحًا من 1 إلى 10.", save: "حفظ وتخصيص", complete: "إكمال الإعداد", saving: "جارٍ حفظ الملف الأكاديمي…", building: "جارٍ تجهيز CampusPulse…", buildingText: "حُفظت مقرراتك. نجهز خلاصتك وتقويمك وبيانات حضورك.", retryTitle: "يحتاج التخصيص إلى محاولة أخرى", retry: "إعادة محاولة التخصيص" },
    settings: { kicker: "تفضيلات الحساب", title: "الإعدادات", subtitle: "تحكم في اللغة والإشعارات والتخصيص الأكاديمي.", interface: "الواجهة", language: "اللغة", timezone: "المنطقة الزمنية", light: "استخدام النمط الفاتح", dark: "استخدام النمط الداكن", delivery: "إرسال الإشعارات", frequency: "التكرار", all: "الكل", important: "المهم", critical: "الحرج فقط", preferred: "الوقت المفضل", dailySummary: "الملخص اليومي", deadlineNotifications: "إشعارات المواعيد النهائية", courseNotifications: "إشعارات المقررات", eventNotifications: "إشعارات الفعاليات", scholarshipNotifications: "إشعارات المنح", academic: "الملف الأكاديمي", academicText: "تغييرات المقررات والاهتمامات تعيد توليد خلاصتك من قاعدة البيانات.", edit: "تعديل الملف الأكاديمي", save: "حفظ الحقول المتغيرة", saving: "جارٍ الحفظ…", saved: "حُفظت الإعدادات في حسابك." },
    live: { unavailable: "الخادم غير متاح", inbox: "أحدث الرسائل", openInbox: "فتح الصندوق", feed: "الخلاصة المخصصة", feedEmpty: "خلاصتك فارغة", feedEmptyText: "لم يُرجع الخادم إشعارات لهذا الحساب.", attendanceUnavailable: "ملخص الحضور غير متاح", safeAttendance: "لا يوجد مقرر تحت حد الحضور 70٪", morning: "صباح الخير", afternoon: "مساء الخير", evening: "مساء الخير" },
    updates: { api: "بيانات مباشرة من واجهة campus-content", all: "الكل", announcements: "الإعلانات", deadlines: "المواعيد النهائية", events: "الفعاليات", scholarships: "المنح", upcoming: "القادمة فقط", allDates: "كل التواريخ" },
    why: { action: "لماذا أرى هذا؟", title: "لماذا هذا؟", loading: "جارٍ تفسير هذه الرسالة…", unavailable: "التفسير غير متاح", none: "لم يُرجع الخادم عوامل إضافية." },
    legal: { pp2: "تُرسل بيانات الحساب والملف الأكاديمي والتفضيلات فقط إلى خادم CampusPulse المضبوط. لا تنشئ الواجهة حسابًا محليًا بديلًا ولا تستبدل سجلات قاعدة البيانات.", pp5: "يمكنك تسجيل الخروج والتواصل مع فريق CampusPulse بشأن البيانات المخزنة لحسابك." },
    calendarAction: { kicker: "إجراء التقويم", attendance: "حضور هذه المحاضرة", submission: "التسليم", markSubmitted: "تحديد كمُسلّم", notSubmitted: "لم يُسلّم بعد", alreadySubmitted: "مُسلّم بالفعل", notification: "حالة الإشعار", alreadyRead: "مقروء بالفعل", markRead: "تحديد كمقروء", archived: "مؤرشف بالفعل", archive: "أرشفة بعد الحفظ", save: "حفظ التغييرات", saving: "جارٍ الحفظ…" },
  },
  ms: {
    system: { loadFailed: "Data ini tidak dapat dimuatkan", retry: "Cuba lagi", emptyResponse: "Pelayan mengembalikan respons kosong." },
    onboarding: { eyebrow: "PENYEDIAAN AKADEMIK", title: "Beritahu kami apa yang patut ada dalam suapan.", subtitle: "Hanya kursus daripada pangkalan data universiti boleh disimpan.", faculty: "Fakulti (pilihan)", major: "Jurusan (pilihan)", year: "Tahun pengajian (1–10)", interests: "Minat", interestHint: "Pilih minat", selectFaculty: "Pilih fakulti", selectMajor: "Pilih jurusan", selectYear: "Pilih tahun", selectInterest: "Pilih minat", add: "Tambah", search: "Cari katalog kursus", searchHint: "Kod, nama kursus atau fakulti", selectError: "Pilih sekurang-kurangnya satu kursus dan satu minat.", yearError: "Tahun pengajian mestilah nombor bulat 1 hingga 10.", save: "Simpan dan peribadikan", complete: "Lengkapkan persediaan", saving: "Menyimpan profil akademik…", building: "Membina CampusPulse anda…", buildingText: "Kursus disimpan. Kami menyediakan suapan, kalendar dan data kehadiran.", retryTitle: "Pemperibadian perlu dicuba lagi", retry: "Cuba pemperibadian lagi" },
    settings: { kicker: "KEUTAMAAN AKAUN", title: "Tetapan", subtitle: "Kawal bahasa, penghantaran dan pemperibadian akademik.", interface: "Antara muka", language: "Bahasa", timezone: "Zon masa", light: "Guna tema cerah", dark: "Guna tema gelap", delivery: "Penghantaran notifikasi", frequency: "Kekerapan", all: "Semua", important: "Penting", critical: "Kritikal sahaja", preferred: "Masa pilihan", dailySummary: "Ringkasan harian", deadlineNotifications: "Notifikasi tarikh akhir", courseNotifications: "Notifikasi kursus", eventNotifications: "Notifikasi acara", scholarshipNotifications: "Notifikasi biasiswa", academic: "Profil akademik", academicText: "Perubahan kursus dan minat menjana semula suapan daripada pangkalan data.", edit: "Edit profil akademik", save: "Simpan medan berubah", saving: "Menyimpan…", saved: "Tetapan disimpan ke akaun anda." },
    live: { unavailable: "Backend tidak tersedia", inbox: "Mesej terkini", openInbox: "Buka peti masuk", feed: "SUAPAN DIPERIBADIKAN", feedEmpty: "Suapan anda kosong", feedEmptyText: "Tiada notifikasi pangkalan data untuk akaun ini.", attendanceUnavailable: "Ringkasan kehadiran tidak tersedia", safeAttendance: "Tiada kursus di bawah ambang kehadiran 70%", morning: "Selamat pagi", afternoon: "Selamat petang", evening: "Selamat malam" },
    updates: { api: "Data langsung daripada API campus-content", all: "Semua", announcements: "Pengumuman", deadlines: "Tarikh akhir", events: "Acara", scholarships: "Biasiswa", upcoming: "Akan datang sahaja", allDates: "Semua tarikh" },
    why: { action: "Mengapa saya melihat ini?", title: "MENGAPA INI?", loading: "Menjelaskan mesej ini…", unavailable: "Penjelasan tidak tersedia", none: "Tiada faktor tambahan dikembalikan." },
    legal: { pp2: "Data akaun, akademik dan keutamaan dihantar hanya ke backend CampusPulse yang dikonfigurasikan. Frontend ini tidak mencipta akaun fallback tempatan atau menggantikan rekod pangkalan data.", pp5: "Anda boleh log keluar dan menghubungi pasukan CampusPulse tentang data yang disimpan untuk akaun anda." },
    calendarAction: { kicker: "TINDAKAN KALENDAR", attendance: "Kehadiran untuk kuliah ini", submission: "Penghantaran", markSubmitted: "Tandakan sebagai dihantar", notSubmitted: "Belum dihantar", alreadySubmitted: "Sudah dihantar", notification: "Status notifikasi", alreadyRead: "Sudah dibaca", markRead: "Tandakan dibaca", archived: "Sudah diarkib", archive: "Arkib selepas menyimpan", save: "Simpan perubahan", saving: "Menyimpan…" },
  },
} as const;

interface CopyTree { [key: string]: string | CopyTree }

function readPath(tree: CopyTree, path: string): string | undefined {
  let current: string | CopyTree | undefined = tree;
  for (const part of path.split(".")) {
    if (typeof current === "string" || !current) return undefined;
    current = current[part];
  }
  return typeof current === "string" ? current : undefined;
}

export function useCampusTranslation() {
  const { i18n } = useTranslation();
  const lang: Lang = i18n.language === "ar" || i18n.language === "ms" ? i18n.language : "en";

  const text = (path: string, variables?: Record<string, string | number>) => {
    const value = readPath(supplementalTranslations[lang] as CopyTree, path) ?? readPath(translations[lang] as CopyTree, path) ?? readPath(supplementalTranslations.en as CopyTree, path) ?? readPath(translations.en as CopyTree, path) ?? path;
    return Object.entries(variables ?? {}).reduce((result, [key, replacement]) => result.replaceAll(`{{${key}}}`, String(replacement)), value);
  };

  return { lang, text, setLanguage: setLang };
}
